### ISSUE TITLE
Setup members page

### ISSUE THREAD

**Issue by Mehret17** [nss-evening-cohort-7/bandz-oversizedmosquitobites#3]
# Story 
As a user, in order to know who the band members are, there should be one card for each band member with their name, position, picture and bio.

# Acceptance Criteria
**When** the page loads 
**Then** there should be two columns of members with their pictures and info
**And** the members data should be present in main.js
**And** the page should be styled to display the data 

# Technical Notes
- var members = [ 
{ name:"",
 imageURL:"",
bio:"",
role:""
}
- members name : MOE SKEETO, BUCK ZAPPA, DJ FIREFLY, RAID CHARLES
- role: "Lead Singer", "Lead guitar", "Drums", "Keys"
- name should have h2 tag and role should be h3 tags bios will be p tags

**Comment by RitaSyed** [comment]
![image](https://user-images.githubusercontent.com/33096456/37376559-bdba62c2-26f2-11e8-9589-c29003b0f851.png)
