### ISSUE TITLE
nav bar

### ISSUE THREAD

**Issue by Mehret17** [nss-evening-cohort-7/bandz-oversizedmosquitobites#8]

**Comment by Mehret17** [comment]
# Story 
As a user, in order to navigate through the pages there should be a nave bar at the top of the home page.

# Acceptance Criteria
**When** the page loads the nav bar links should work and navigate to the specified pages
**Then** nav bar should display on top of the page 
**And** the logo and the band name should display at the left side of the nav bar and the rest of the links should display to the right

# Technical Notes
- nav bar should have links to member.html, schedule.html, merch.html, disco.html, index.html
- the logo should link to index.html page

**Comment by Mehret17** [comment]
![image](https://user-images.githubusercontent.com/36495588/37378489-687152b6-26fd-11e8-970c-4a091e3886c3.png)

**Comment by RitaSyed** [comment]
Nav bar works good!
